---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Lint code
        run: npm run lint
      - name: Validate server startup
        run: |
          timeout 10s npm start -- --vault-path ./ || exit_code=$?
          if [ "$exit_code" -ne 124 ] && [ "$exit_code" -ne 0 ]; then
            echo "Server failed to start properly"
            exit 1
          fi
          echo "Server validation passed"
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run security audit
        run: npm audit --audit-level moderate
      - name: Check for outdated dependencies
        run: npm outdated || true
